version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  base:
    <<: *restart_policy
    build:
      # Pro-tip: point this to a relative directory containing the Dispatch
      # project root to pick up changes from your dev environment
      # (e.g., ../dispatch-root)
      context: "."
      dockerfile: Dockerfile.base
    image: gcr.io/unity-ie-sre-isolated-test/dispatch:base
    env_file:
      - .env.local
  server:
    <<: *restart_policy
    build:
      # Pro-tip: point this to a relative directory containing the Dispatch
      # project root to pick up changes from your dev environment
      # (e.g., ../dispatch-root)
      context: "."
    image: gcr.io/unity-ie-sre-isolated-test/dispatch:server
    depends_on:
      - base
      - postgres
    env_file:
      - .env.local
    command: ["/venv/bin/dispatch", "server", "start", "dispatch.main:app", "--host=0.0.0.0"]
    ports:
      - "8000:8000"
  ui:
    <<: *restart_policy
    build:
      # Pro-tip: point this to a relative directory containing the Dispatch
      # project root to pick up changes from your dev environment
      # (e.g., ../dispatch-root)
      context: "./ui"
    image: gcr.io/unity-ie-sre-isolated-test/dispatch:ui
    depends_on:
      - postgres
    env_file:
      - ui/.env.local
    ports:
      - "3000:80"
  postgres:
    <<: *restart_policy
    env_file:
      - .env
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
volumes:
  dispatch-postgres:
    external: true
