"""empty message

Revision ID: 5c0efb2ab266
Revises: 69ac7f6dc0da
Create Date: 2020-07-15 18:02:55.783848

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5c0efb2ab266'
down_revision = '69ac7f6dc0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_user', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_dispatch_user_search_vector', 'dispatch_user', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('incident', sa.Column('duplicate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incident', 'incident', ['duplicate_id'], ['id'])
    op.add_column('term', sa.Column('discoverable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('term', 'discoverable')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_column('incident', 'duplicate_id')
    op.drop_index('ix_dispatch_user_search_vector', table_name='dispatch_user')
    op.drop_column('dispatch_user', 'search_vector')
    # ### end Alembic commands ###
