apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    prometheus.io/name: {{ .Values.name }}
    prometheus.io/path: "{{ .Values.service.prometheus_path }}"
    prometheus.io/port: "{{ .Values.service.prometheus_port }}"
    prometheus.io/scrape: "{{ .Values.service.prometheus_scrape }}"
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.name }}
  selector:
    app: {{ .Values.name }}
