apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{ .Values.ingress.name}}
    namespace: sre
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.ingress.cors.enabled }}"
        nginx.ingress.kubernetes.io/cors-allow-methods: "{{ .Values.ingress.cors.allowMethods }}"
        nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.cors.allowOrigin }}"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "{{ .Values.ingress.cors.allowCredentials }}"
spec:
    rules:
        - host: {{ .Values.ingress.host }}
          http:
            paths:
            - path: /
              backend:
                serviceName: xray
                servicePort: xray

    tls:
        - hosts:
              - {{ .Values.ingress.host }}
          secretName: wildcard-sre
